language: node_js
sudo: false
node_js:
  - 8

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn run test && yarn run cover

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - cat ./coverage/lcov.info  | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js
